# temporary fix for bug: 
#   https://github.com/spring-cloud/spring-cloud-commons/issues/355 ,
#   https://github.com/spring-projects/spring-boot/issues/13042
spring:
  cloud:
    refresh:
      refreshable: false

#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 25000

# SocketTimeoutException in config server on connecting to GitHub when commented out
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 6000

# Expose all actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*" # For production you should carefully choose which endpoints to expose
  endpoint:
    health:
      showDetails: always #show details in actuator/health endpoint
        
# management.endpoints.web.exposure.exclude: env,beans
# management.endpoints.jmx.exposure.include: "*"


#hystrix:
#  shareSecurityContext: true # Fix for: Error creating bean with name 'scopedTarget.oauth2ClientContext': Scope 'request' is not active for the current thread
