# temporary fix for bug: 
#   https://github.com/spring-cloud/spring-cloud-commons/issues/355 ,
#   https://github.com/spring-projects/spring-boot/issues/13042
spring.cloud.refresh.refreshable: false

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 8000
ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 5000

# Expose all actuator endpoints
management.endpoints.web.exposure.include: "*"
# management.endpoints.web.exposure.exclude: env,beans

management.endpoint.health.showDetails: when-authorized #show details in actuator/health endpoint